name: my_dart_rest
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: veshkin <veshkin@action-media.ru>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  jaguar: ^2.4.36

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
